### ISSUE TITLE
Nothing is showing after installing 

### ISSUE THREAD

**Issue by ppdcom** [tierra/topicsolved#12]
I have just installed it in 3.1.3 and I cannot use its options. please guide

**Comment by tierra** [comment]
What steps have you taken to install it? Where is it installed? Did you enable it?

**Comment by ppdcom** [comment]
I have installed it in /ext/tierra/topicsolved and then enabled it from ACP to `Customise -> Manage extensions`.  then its activated but I cannot see any settings in Extension menu or in post editing tool.

Thanks

**Comment by tierra** [comment]
The settings are found in the Forum settings page.

**Comment by ppdcom** [comment]
![snag-0000](https://cloud.githubusercontent.com/assets/1098177/6434374/53e9504a-c0a9-11e4-991a-3892104e92aa.jpg)

Sorry.. I did not find this in instructions... I found these options now. Will check and test further. Thanks for great extension and work. Looking forward for stable release.

**Comment by tierra** [comment]
Just FYI, I've added a new section to the docs for "Getting Started":
https://github.com/tierra/topicsolved#getting-started

You're not the first person to be confused trying to find those settings.

**Comment by ppdcom** [comment]
Many Thanks, Its make sense now having some document for extension so new user will not be confused. Wordpress most plugin have detailed documents but for phpbb specially v3 I did not see proper instructions or documentation  for extension. I think developers should consider it part of the module.
