### ISSUE TITLE
If a topic solved is locked - then unlocked - and that topic is reopened this topic will be locked

### ISSUE THREAD

**Issue by Galixte** [tierra/topicsolved#15]
Hi,

with those parameters :

```
Topic solved settings
Allow topics to be marked as solved: Yes
Allow topics to be reopened: Yes
Lock solved topics: Yes
```

If a user named "A" creates a topic for a question. Then many users respond on it. After that a response was published by a user "B", the user A marks the topic as solved and the topic is locked (see above my settings). At last, if a moderator user "C" wants to unlock this topic to allow some users to respond again and that the user "A" wants to reopen his topic (as unsolved) the topic will be unsolved (it's OK) but it will be locked.

I hope my explanations are clear

**Comment by tierra** [comment]
In your explanation, you seem to indicate that moderator "C" actually unlocked the topic, so it should in fact be unlocked.

I think I see what you're getting at though. It's true that when "Lock solved topics" is on, it actually bypasses any "lock topic" permissions configured, and allows the topic author (A) to lock their own topic even if they don't have permission to. At that point, they can "unsolve" their post still, but not unlock their topic.

Maybe when locking topics is turned on, it should probably only lock if the user has permission to lock topics. That way you can configure your board to either allow users to lock/unlock their own topics, or only allow moderators to lock/unlock even when marking a topic as solved.

**Comment by tierra** [comment]
Or are you saying that the topic won't actually unlock properly?

**Comment by Galixte** [comment]
"In your explanation, you seem to indicate that moderator "C" actually unlocked the topic, so it should in fact be unlocked." => it should be unlocked after the moderator action, yes

"Maybe when locking topics is turned on, it should probably only lock if the user has permission to lock topics. That way you can configure your board to either allow users to lock/unlock their own topics, or only allow moderators to lock/unlock even when marking a topic as solved." => yes i can but for me this situation it's like a bug.

"Or are you saying that the topic won't actually unlock properly?" => I can not say this with certainly. After the moderator has unlocked the subject, I cannot see the REPLY button marked as locked, so I presume that the subject has been unlocked by the moderator.

Are you able to reproduce my problem ?

**Comment by Galixte** [comment]
"In your explanation, you seem to indicate that moderator "C" actually unlocked the topic, so it should in fact be unlocked." => it should be unlocked after the moderator action, yes

"Maybe when locking topics is turned on, it should probably only lock if the user has permission to lock topics. That way you can configure your board to either allow users to lock/unlock their own topics, or only allow moderators to lock/unlock even when marking a topic as solved." => yes i can but for me this situation it's like a bug.

**Comment by tierra** [comment]
How is it like a bug?

I don't think I'm entirely clear on what your problem is, or how you expect it to work.

**Comment by Galixte** [comment]
In fact, I just tested with an administrator and once that topic is locked when I press the SOLVED button several times, the topic changes from state "NOT SOLVED" to "SOLVED" to "NOT SOLVED" etc ... but the topic remains always locked.

**Comment by tierra** [comment]
Right, the "lock solved topics" was only ever intended to work one way (to lock the topic when it's marked as solved). It isn't supposed to unlock any topics when someone marks it as unsolved.

**Comment by Galixte** [comment]
Ok that what I'm talking about for me it does not make sense.

If the status of the topic changes to be "not solved" its status must be changed to be unlocked.

**Comment by tierra** [comment]
What I'm trying to clarify is that by default, users technically shouldn't even be allowed to lock or unlock a topic at all unless the administrator has configured the forum to allow regular users to lock and unlock topics. This is actually controlled by a built in permission in the administration panel, and has nothing to do with this extension. Look for the "Can lock own topics" forum permission, you can change that permission in the forums, or the user roles (assuming you're using those roles in the permissions).

If you change "Can lock own topics" to "Yes" for your forum, for the role used by regular users, they'll actually have the permissions required to unlock topics, regardless of whether you have the Topic Solved extension installed or not.

Right now, Topic Solved bypasses that permission check when locking topics. It actually isn't supposed to. And that's why I'm not planning on additionally bypassing the check in order to unlock topics as well, not unless that permission is set to "Yes" at least.

**Comment by Galixte** [comment]
On my forum if If i change "Can lock own topics" to "Yes" for my forum, for the role used by regular users,  they actually don't have the permissions required to unlock topics.

**Comment by tierra** [comment]
phpBB permissions can be tricky to understand correctly, it might help to read up on how permissions work:
https://www.phpbb.com/support/docs/en/3.1/ug/adminguide/permissions_forumbased/

**Comment by tierra** [comment]
Testing this out myself a little more, it looks like that permission still doesn't allow regular users to unlock their own topics, only to lock it. So I guess the ability to unlock a topic is specifically restricted only to moderators.

**Comment by tierra** [comment]
It's also worth noting that the extension does not allow anyone (not even a moderator) to mark a topic as solved or unsolved when the topic is locked.

So if you turned on "lock solved topics", no-one can actually mark the topic as unsolved until it is manually unlocked by a moderator first.

**Comment by tierra** [comment]
I've opened a new issue with the task of checking those permissions: #16

Other than that, unlocking a topic when marking it as unsolved is an invalid issue since it's not possible to mark a topic as unsolved anyway if it's locked. It has to be unlocked first by a moderator with the permission to do so.

**Comment by tierra** [comment]
Actually, I guess even moderators and admins can still mark a topic as unsolved or edit the post when it's locked. Sorry, I just confused myself.

So then the question is only relevant for moderators, not regular users. Should the topic be unlocked when marking as unsolved by a moderator, assuming they have the permission to unlock topics?

**Comment by tierra** [comment]
Even if the topic isn't automatically unlocked when marking as unsolved, usually the moderators do have the permission to unlock the topic manually, so this is really much less of an issue though.

**Comment by tierra** [comment]
I've opened #17 to start fresh with a task that's clear to it's purpose up front. Please continue any new discussion there.
