### ISSUE TITLE
Translations Broken in Admin Panel

### ISSUE THREAD

**Issue by tierra** [tierra/topicsolved#20]
There's been a couple reports of translations not being properly loaded in the ACP.

**Comment by Galixte** [comment]
Hi,

french translation is concerned ?

**Comment by tierra** [comment]
I'm not sure which ones yet, but there's been one report that the [Dutch translation isn't working right](https://www.phpbb.com/community/viewtopic.php?p=14012151#p14012151), and another report that [none of the translations load correctly](https://www.phpbb.com/community/viewtopic.php?p=14059221#p14059221).

**Comment by Galixte** [comment]
For me in French on phpBB 3.1.3 it was OK, i will test on phpBB 3.1.4.

Otherwise for arabic language, i seen on phpbb-fr.com (french support board) that a user had the same problem.

Maybe the PHP version.

**Comment by tierra** [comment]
I tried to reproduce the problem, but was unable to. I confirmed that all of the following languages are loading properly (including in the ACP):
- Dutch
- French
- Russian
- Spanish
- Swedish
- Turkish

And in the situation where a language is installed for phpBB, but isn't supported by Topic Solved, it falls back to British English like it's supposed to. So there's nothing broken there either.

**Comment by Galixte** [comment]
Have you tested this case with different versions of PHP ?

**Comment by tierra** [comment]
Just PHP 5.5 locally, but this issue is something that can (and does) happen when the administrator fails to clear the phpBB cache after upgrading an extension. So I'm fairly certain this is actually the reason some users are running into this.

I'll be adding some functional tests to cover this at some point though, so it will cover 5.3, 5.4, 5.5, 5.6, and HHVM soon.

**Comment by tierra** [comment]
Some new information was made available today that suggests that phpBB only automatically loads the first `info_acp_*.php` file that it finds in the folder as opposed to all `info_acp_*.php` files. The `info_acp_styles.php` file only contains strings used as alternative icon text that I included from the old Topic Solved MOD since it was used there, but I haven't used them yet in the new extension, so it's possible that I just haven't noticed that they weren't being loaded.

So I'm going to reopen this, and verify if this is the case. If it is, the fix is pretty simple: just include the strings all in one `info_acp_topicsolved.php` file.

**Comment by tierra** [comment]
Ok, I've tracked this down finally, and was able to verify my suspicions noted earlier: it is a bug in phpBB causing this. It turns out someone else also just reported the issue causing this problem a week ago in fact:
https://tracker.phpbb.com/browse/PHPBB3-13868

Also see this post for more info:
https://www.phpbb.com/community/viewtopic.php?p=14099821#p14099821

So the remaining task to fix this in the extension is to combine all `info_acp_styles.php` and `info_acp_forums.php` language files into one file. I'll get this done soon here.
