### ISSUE TITLE
Implement Transifex System for Translations

### ISSUE THREAD

**Issue by tierra** [tierra/topicsolved#28]
Currently translators are required to manually download all source translation files, check them for updates, manually update each individual language file, and either package them up for myself to commit to the repo, or create a pull request themselves. This is a terrible system for managing translations, and doesn't provide any way to notify translators of changes to strings, or upcoming releases. It also doesn't make it easy for multiple translators to collaborate on the same languages. It also puts a larger workload on myself to keep these translations updated, and it's prone to syntax errors in PHP language files.

Instead, I'd like to eventually setup this extension to automatically upload all source translation changes to Transifex, where translators can be notified of changes, and provide updates to individual languages without be required to download or upload files at all. Translators will also no longer be required to understand git or PHP in order to provide translations. This can even be configured to automatically push updates for each language directly into the latest development version of the extension.

All past, current and future translators should subscribe to updates on this ticket to be notified when I finally get around to implementing this system so you have a chance to sign up as a translator on this project.

I have already created a Transifex project for this, so even though it's not being used yet, you can still sign up now to be a translator, and will be notified automatically there once I have the strings being pushed there. Here's a link to the project:
- https://www.transifex.com/projects/p/phpbb-topic-solved/

**Comment by Galixte** [comment]
When you would to use this system ? i’m already registered on your transifex project.

**Comment by tierra** [comment]
I still haven't done much work on getting this configured yet, but hope to sooner rather than later. The earlier I'm able to get it working, the better chance I have of getting new translators on board with providing updates to the new languages still being added like the latest Danish, Portuguese, and German.

Just curious, have you used Transifex with any other projects yet? It seems to be getting fairly popular with open source projects, although I still haven't seen any phpBB-related projects using it yet.

**Comment by tierra** [comment]
The good news is that I haven't had to do any string changes that need updates with any of the translations, even the first ones submitted, so they're all still at 100%.

**Comment by Galixte** [comment]
No, I haven’t yet had the opportunity to work with.

**Comment by tierra** [comment]
Translation resources have now been added to Transifex, and are ready to be used from here from now on. All new translations should be requested and submitted to the Transifex project:

https://www.transifex.com/tierra/phpbb-topic-solved/
