### ISSUE TITLE
compatibility with Thanks for posts extension

### ISSUE THREAD

**Issue by Galixte** [tierra/topicsolved#30]
Hi @tierra,

it seems there is a problem with Thanks for posts extension (https://github.com/rxu/thanks_for_posts), see here: https://www.phpbb.com/community/viewtopic.php?p=14122346#p14122346.

**Comment by Galixte** [comment]
Hi @tierra,

I explained my test about this issue here: https://github.com/rxu/thanks_for_posts/issues/41.

**Comment by tierra** [comment]
Thanks, I'll keep an eye on this, but it sounds like a problem caused by the Thanks for Posts extension.

**Comment by Galixte** [comment]
Of course, but I 'm to promote exchange of expertise between author extensions. ;)
