### ISSUE TITLE
Compability with QuickReply Reloaded?

### ISSUE THREAD

**Issue by BlackSkorpio** [tierra/topicsolved#44]
Is there any plans on doing topic solved compatible with 
https://www.phpbb.com/community/viewtopic.php?p=14328926#p14328926

Would be awesome to be able to use both extensions

As it now, when enabling the above: it seams to remove the topic solved marker for the post.

**Comment by tierra** [comment]
So it just doesn't show the topic solved indicator for the topic? Or does it not show the post button for marking the topic as solved (with the post created with quick reply)? I haven't installed or tested that extension, but it might be nice to get some clarification about what isn't working correctly.

**Comment by BlackSkorpio** [comment]
The indicator is shown for the thread/topic and the solved button is also shown as it should
But the solved indicator that gets attached to the solving answer is removed

**Comment by BlackSkorpio** [comment]
@tierra Not meant to "nagg you" in anyway, but wondering if there is any progress on this issue?

**Comment by BlackSkorpio** [comment]
Closing this and goes to hide in the "shame corner"!
It turns out that the Quick reply reloaded ext hides the setting: "Show posts subjects in topics:" is by default set to "No"
