### ISSUE TITLE
Prosilver 2 compatibility

### ISSUE THREAD

**Issue by bagda391** [tierra/topicsolved#45]
Hey!

It looks like prosilver does not work with this. Any help? I enabled extension but nothing showing up. 

Thanks.

**Comment by bagda391** [comment]
Edit: is it because I also have Thanksforpost module?

**Comment by lavigor** [comment]
@bagda391 please check out the latest version of Thanks for posts extension in its GitHub repository (https://github.com/rxu/thanks_for_posts).
It was a known problem some time ago.
