### ISSUE TITLE
Add buttons.css to ALL theme to prevent fatal error on install

### ISSUE THREAD

**Issue by tripflex** [tierra/topicsolved#50]
It may be a good idea to just go ahead and add the buttons.css file to the `all/theme` directory, as if theme support is not already included in this extension, there will be a fatal error ... at least with having the `buttons.css` file in the `all/theme` directory, it won't throw a fatal error, the button just may not look they way they want it.  I'm a dev so this was easy fix for me, but i'm sure there are others that this may really mess with them.

https://github.com/tierra/topicsolved/blob/master/styles/prosilver/theme/buttons.css

**Comment by tierra** [comment]
This has been done in 8e4bc72218129135c203176b5c10d5d7100d69f5 now.
