### ISSUE TITLE
How to move the solved-image/text

### ISSUE THREAD

**Issue by raykai** [tierra/topicsolved#62]
Hi,
im looking for a way to move the solved text to the front of the topic name.
Any help would be appreciated.
![how](https://user-images.githubusercontent.com/8138894/29755483-c17cde4e-8b66-11e7-9206-8fc7e22c45e3.JPG)

**Comment by Galixte** [comment]
Hi @raykai,

try to rename this file name: https://github.com/tierra/topicsolved/blob/master/styles/all/template/event/viewtopic_topic_title_append.html to ```topiclist_topic_title_prepend.html```, then purge your board cache.

**Comment by raykai** [comment]
that's not working :(

**Comment by Galixte** [comment]
Hi @tierra could you take a look, please?

**Comment by raykai** [comment]
please! i really need this. cant seem to add css for moving it either :(

**Comment by tierra** [comment]
This is a duplicate of #26 

Sorry, this is an unsupported feature (currently), and I don't provide help with custom hacks to make it work.
