### ISSUE TITLE
Marking topic solved (or unsolved) forces login again

### ISSUE THREAD

**Issue by tbird1965** [tierra/topicsolved#63]
When I mark my topic as solved, the login screen is loaded and I must login again.  The topic is marked as solved.  The same occurs if I mark a solved topic as unsolved.  Is this the intent or is there an issue with this app and 3.2.1?  Please contact me if there is any additional information you need.

Running phpBB 3.2.1
Prosilver with some color changes (otherwise stock style)

**Comment by tierra** [comment]
Others have run into the same problem in the past, and solved it by ensuring they have their cookie settings for the board configured correctly.

There wasn't much detail given about what was configured wrong, but I'm certain this is the same problem: https://www.phpbb.com/community/viewtopic.php?p=13996471#p13996471

**Comment by tbird1965** [comment]
NOT A BUG.  Yes, it was with the cookie settings.  I am testing this plugin on a test system which does not have the usual URL.  So the error was the cookie domain was still setup for the real site.  Changing the cookie domain to the IP address of my test site solved it.  Works great - thank you!

**Comment by tierra** [comment]
Thanks for providing more details on that
