### ISSUE TITLE
Font Awesome

### ISSUE THREAD

**Issue by Galixte** [tierra/topicsolved#64]
@tierra,

i’m prettu syre to have seen a version from your extension with font Awesome used  for the check mark.

Do you know about this version or i maked a beautiful dream about that?

**Comment by tierra** [comment]
Not a dream, it's what gets used if you upgrade to phpBB 3.2, and install the extension from the latest master branch. I just haven't built a new release yet.

**Comment by Galixte** [comment]
Ok, thanks for informations. ;)
