### ISSUE TITLE
Css issue for prosilver style?

### ISSUE THREAD

**Issue by WassMM** [tierra/topicsolved#67]
I installed the phpbb 3.2.1 from scratch and use only default settings. Added the extension and it looks like this:

![image](https://user-images.githubusercontent.com/13963337/33938323-6b0eb1cc-e007-11e7-818c-575ff778b024.png)

Please advise

**Comment by tierra** [comment]
You should download the latest development version of this extension. The latest release doesn't have support for phpBB 3.2 yet.

https://github.com/tierra/topicsolved/archive/master.zip

**Comment by WassMM** [comment]
It works! Thank you!
