### ISSUE TITLE
Any idea why this extension doesn't work on phpbb3.2?

### ISSUE THREAD

**Issue by luzpaz** [tierra/topicsolved#69]
Here is the [thread](https://forum.freecadweb.org/viewtopic.php?f=8&t=26340&hilit=phpbb+topic+solved#p209085) on FreeCAD forums that is running 3.2.x

**Comment by tierra** [comment]
It is compatible with 3.2, just not in any of the official releases. You have to checkout the master branch, or download a generated ZIP of the master branch here:
https://github.com/tierra/topicsolved/archive/master.zip

**Comment by tierra** [comment]
Also see: 8e4bc72218129135c203176b5c10d5d7100d69f5
