### ISSUE TITLE
Button too small

### ISSUE THREAD

**Issue by Herve-be** [tierra/topicsolved#72]
Hi,
I've installed this extension 2.2.0 on phpBB 3.3.0 and corrected the .yml file, it works but

- the "solved" button is too small, see red circle
- I have a lot of OK signs instead of one; if I use text it's ok

Can you help ?
Thanks
![Solved](https://user-images.githubusercontent.com/42873018/78163171-4ad28780-7448-11ea-864d-0972354a2524.jpg)

**Comment by tierra** [comment]
You need 2.3.0, not 2.2.0 for phpBB 3.2 and later:
- https://github.com/tierra/topicsolved/releases/tag/2.3.0

That release will still need those YML corrections for phpBB 3.3+ though.

**Comment by Galixte** [comment]
@Herve-be take a look about that for the fix for phpBB 3.3.x: https://github.com/tierra/topicsolved/issues/71#issuecomment-593045654.

**Comment by Herve-be** [comment]
@Galixte as I've said Ihad modified the .yml file without success.
@tierra I didn't saw there was a version 2.3.0 : it works fine now, thanks.
