### ISSUE TITLE
Topic Solved icon not display in one forum category

### ISSUE THREAD

**Issue by Xicor33** [tierra/topicsolved#78]
Hello, I have an issue on only one category of my forum. The icon topics solved is not display in the topics right side (see picture)
![2021-11-17 09_31_38 no icon](https://user-images.githubusercontent.com/54192353/142163939-87680d5b-98ba-4133-a064-e37cdacc0b51.png)
In all others category of the same forum, the icon is displayed and I can mark them at solved....
I have check the Forum settings in ACP but they are all the same...
Do you have any idea where I can have a look.
Thanks a lot

**Comment by tierra** [comment]
Sounds like you've already followed the [Getting Started](https://github.com/tierra/topicsolved/blob/master/readme.md#getting-started) instructions (but I'm linking them here anyway in case).

Other than that, if it's showing correctly on other forums on the same board, then clearly it's compatible with your skin (and it looks like you're just using the default prosilver anyway, which is definitely supported).

I'm not sure what else you could check, but probably worth ensuring that the forum page isn't being cached by the server or your browser.

**Comment by Xicor33** [comment]
Hello,
thanks for the advise.
Solved the isssue in ADP by setting Type forums from Forum to Category then save.
Then setting back to Forum.
The solved icons is now displayed
