### ISSUE TITLE
Color Picker for Custom Text Color

### ISSUE THREAD

**Issue by tierra** [tierra/topicsolved#8]
Currently, the custom color used for text solved indicators must be input manually as a CSS hex value in the ACP. It would be nice to replace this input with a more user-friendly color swatch using some kind of JavaScript-based color picker.

**Comment by Galixte** [comment]
Hi,

thanks, it’s a good idea, greetings !

**Comment by tierra** [comment]
Turned out to be really easy, I just used the built-in swatch used for group colours. :)
